---
title: "SAE Project"
author: "Group 3"
date: "`r Sys.Date()`"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
# Packages
library(haven)
library(dplyr)
library(readxl)
library(sae)
library(msaeDB)
```

```{r, message=FALSE, warning=FALSE}
# Dataset
data_final <- read_sav("data_final.sav")          # Main Dataset
          
data <- read_sav("KOR23GAB_saeProject.sav")     # Predictor Dataset

PODES21_auxvar_1 <- read_sav("PODES21_auxvar_1.sav")       # Podes Dataset 1
PODES21_auxvar_2 <- read_sav("PODES21_auxvar_2.sav")       # Podes Dataset 2
PODES21_auxvar_3 <- read_sav("PODES21_auxvar_3.sav")       # Podes Dataset 3
PODES21_auxvar_4 <- read_sav("PODES21_auxvar_4.sav")       # Podes Dataset 4

```


```{r}
kode <- unique(PODES21_auxvar_1[,c(3,5)]) %>%
  rename(
    Provinsi = r101n,
    Kabupaten = r102n
  )

gab <- left_join(kode, data_final[,c(1,3,5)], by = "Kabupaten") %>%
  mutate(
    kat_Nondis = ifelse(is.na(RSE_Nondis), "NA",
                        ifelse(RSE_Nondis >= 50, "Lebih dari 50 Persen",
                               ifelse(RSE_Nondis >= 25, "RSE 25 - 50 Persen",
                                      ifelse(RSE_Nondis > 0, "RSE 0 - 25 Persen", "RSE 0")))),
    kat_Disab = ifelse(is.na(RSE_Disab), "NA",
                       ifelse(RSE_Disab >= 50, "Lebih dari 50 Persen",
                              ifelse(RSE_Disab >= 25, "RSE 25 - 50 Persen",
                                     ifelse(RSE_Disab > 0, "RSE 0 - 25 Persen", "RSE 0"))))
    )

table(factor(gab$Provinsi),factor(gab$kat_Disab))
```


```{r}
# Eksplorasi
clean <- data %>%
  filter(R407 >= 7 & R407 <= 17) %>%
  mutate(KODE = paste0(R101,R102)) %>%
  mutate(DISAB = ifelse((R1002 == 1 | R1002 == 2) |
                        (R1003 == 5 | R1003 == 6) | 
                        (R1004 == 1 | R1004 == 2) |
                        (R1005 == 5 | R1005 == 6) |
                        (R1006 == 1 | R1006 == 2) |
                        (R1007 == 5 | R1007 == 6) |
                        (R1008 == 1 | R1008 == 2) |
                        (R1009 == 5 | R1009 == 6), 1, 0)) %>%
  mutate(SEKUL = ifelse(R610 == 2, 1, 0)) %>%
  mutate(DISAB_SEKUL = ifelse(DISAB == 1 & SEKUL == 1, 1, 0)) %>%
  mutate(DISAB_NON_SEKUL = ifelse(DISAB == 1 & SEKUL == 0, 1, 0)) %>%
  mutate(NON_DISAB_SEKUL = ifelse(DISAB == 0 & SEKUL == 1, 1, 0)) %>%
  mutate(NON_DISAB_NON_SEKUL = ifelse(DISAB == 0 & SEKUL == 0, 1, 0)) %>%
  select(c(KODE,DISAB,SEKUL,DISAB_SEKUL,DISAB_NON_SEKUL,NON_DISAB_SEKUL,NON_DISAB_NON_SEKUL))

clean <- clean %>%
  group_by(KODE) %>%
  summarise(
    jumlah_sampel = sum(DISAB),
    jumlah_sampel_disab = sum(DISAB == 1),
    jumlah_sampel_tidak = sum(DISAB == 0),
    jumlah_sekolah = sum(SEKUL),
    jumlah_sekolah_disab = sum(DISAB_SEKUL == 1),
    jumlah_sekolah_tidak = sum(NON_DISAB_SEKUL == 1)
  )
```


```{r}
data1 <- PODES21_auxvar_1 %>%
  rename(Kabupaten = r102n) %>%
  group_by(Kabupaten) %>%
  summarise(jumlah_deskel = n(),
            permukiman_kumuh = sum(r512a == 1),
            desa_dalam_hutan = sum(r309a == 1),      
            desa_tepi_hutan = sum(r309a == 2),
            desa_luar_hutan = sum(r309a == 3),
            desa_ketinggian_lebih_200 = sum(r307b2 >= 200),
            desa_ketinggian_kurang_200 = sum(r307b2 < 200),
            desa_penerangan_jalan = sum(r502b == 1| r502b == 2),
            desa_tanpa_penerangan_jalan = sum(r502b == 3),
            penghasilan_utama_pertanian = sum(r403a == 1),
            desa_airminum_bukan_kemasan = sum(r507a == 3| r507a == 4| r507a == 5|
                                              r507a == 6| r507a == 7| r507a == 8|
                                              r507a == 9| r507a == 10),
            keluarga_bukan_listrik = sum(r501b),
            )

data2 <- PODES21_auxvar_2 %>%
  rename(Kabupaten = r102n) %>%
  group_by(Kabupaten) %>%
  summarise(jumlah_SKTM = sum(r711),
            jumlah_sarana_kesehatan = sum(r704ak2|r704bk2|r704ck2|r704dk2|r704ek2|
                                          r704fk2|r704gk2|r704hk2|r704ik2|r704lk2|
                                          r704mk2),
            jumlah_faskes_lain = sum(r704bk2|r704ck2|r704dk2|r704ek2|
                                     r704fk2|r704gk2|r704hk2|r704ik2|
                                     r704jk2|r704kk2|r704lk2|r704mk2),
            jumlah_tenaga_kesehatan = sum(r706a1|r706a2|r706b|r706c|r706d),
            jumlah_faskes = sum(r704ak2|r704bk2|r704ck2|r704dk2|
                                r704ek2|r704fk2|r704gk2|r704hk2|
                                r704ik2|r704jk2|r704kk2|r704lk2|r704mk2),
            jumlah_warga_kekurangan_gizi = sum(r710)
            )

data3 <- PODES21_auxvar_3 %>%
  rename(Kabupaten = r102n) %>%
  group_by(Kabupaten) %>%
  summarise(jumlah_desa_sinyal_kuat = sum(r1005c == 1|r1005c == 2),
            jumlah_desa_sinyal_4G = sum(r1005c == 1),
            jumlah_desa_sebagian_besar_ponsel = sum(r1003b == 1),
            jumlah_desa_sebagian_kecil_ponsel = sum(r1003b == 2),
            jumlah_desa_tidak_ada_ponsel = sum(r1003b == 3),
            jumlah_desa_lalu_lintas_darat = sum(r1001a == 1),
            jumlah_desa_lalu_lintas_lainnya = sum(r1001a == 2|r1001a == 3|r1001a == 4),
            jumlah_desa_aspal = sum(r1001b1 == 1),
            jumlah_desa_angkutan_umum = sum(r1001c1 == 1 | r1001c1 == 2),
            jumlah_koperasi_simpan_pinjam = sum(r1206a3),
            jumlah_koperasi_lainnya = sum(r1206a4)
            )

data4 <- PODES21_auxvar_4 %>%
  rename(Kabupaten = r102n) %>%
  group_by(Kabupaten) %>%
  summarise(jumlah_korban_bunuh_diri = sum(r1307ak2|r1307ak3)
  )

```


```{r}
# Merge Dataset Podes
data_merge <- full_join(data1, data2, by = "Kabupaten")
data_merge <- full_join(data_merge, data3, by = "Kabupaten")
data_merge <- full_join(data_merge, data4, by = "Kabupaten")
data_merge <- full_join(data_final, data_merge, by = "Kabupaten")

```


```{r}
data_olah <- data_merge %>%
  mutate(
    APS_Nondis = APS_Nondis/100,
    APS_Disab = APS_Disab/100,
    jumlah_desa_aspal = ifelse(is.na(jumlah_desa_aspal),0,jumlah_desa_aspal),
    persen_perkotaan = (jumlah_kota/jumlah_deskel)*100,
    persen_perdesaan = (jumlah_desa/jumlah_deskel)*100,
    persen_kumuh = (permukiman_kumuh/jumlah_deskel)*100,
    Persen_desa_dalam_hutan = (desa_dalam_hutan/jumlah_deskel)*100,
    Persen_desa_tepi_hutan = (desa_tepi_hutan/jumlah_deskel)*100,
    Persen_desa_luar_hutan = (desa_luar_hutan/jumlah_deskel)*100,
    Persen_desa_ketinggian_lebih_200 = (desa_ketinggian_lebih_200/jumlah_deskel)*100,
    Persen_desa_ketinggian_kurang_200 = (desa_ketinggian_kurang_200/jumlah_deskel)*100,
    Rasio_bts_luas = jumlah_menara_bts/luas_wilayah,
    Rasio_desa_kota = jumlah_kota/jumlah_deskel,
    Rasio_desa_luar_dalam = desa_luar_hutan/desa_dalam_hutan,
    Rasio_desa_luar_dalam = ifelse(is.infinite(Rasio_desa_luar_dalam),0,Rasio_desa_luar_dalam),
    Rasio_murid_sd = murid_sd/jumlah_sd,
    Rasio_murid_smp = murid_smp/jumlah_smp,
    Rasio_murid_sma = murid_sma/jumlah_sma,
    Rasio_murid_slb = murid_slb/jumlah_slb,
    Rasio_nakes_faskes = jumlah_tenaga_kesehatan/jumlah_faskes,
    Rasio_aspal_darat = jumlah_desa_aspal/jumlah_desa_lalu_lintas_darat,
    Rasio_angkutan_umum_darat = jumlah_desa_angkutan_umum/jumlah_desa_lalu_lintas_darat,
    Rasio_simpan_pinjam_lainnya = jumlah_koperasi_simpan_pinjam/jumlah_koperasi_lainnya
  )

data_olah
```


```{r}
# Membuat dataset khusus pengolahan
data_olahan_rasio <- data_olah[,c(4,5,60:70)]
data_olahan_persen <- data_olah[,c(4,5,52:59)]
data_olahan_jumlah <- data_olah[,c(4,5,7:12,14:21,23:29,31,34,37:40,42,45,47:49)]
```

## Cek Korelasi Data Jumlah
```{r}
# Membuat data frame kosong
results_jumlah <- data.frame(Variable = character(),
                      Correlation = numeric(),
                      Cutoff = character(),
                      P_Value = numeric(),
                      Decision = character(),
                      stringsAsFactors = FALSE)

# Melakukan iterasi untuk setiap kolom dalam data_olahan_jumlah
for (i in 1:(ncol(data_olahan_jumlah))) {
  # Menghitung uji korelasi
  a <- cor.test(x = data_olahan_jumlah[[i]], y = data_olahan_jumlah$APS_Disab, method = "spearman")
  
  # Menentukan keputusan berdasarkan p-value
  cutoff <- ifelse(abs(a$estimate) >= 0.5, "Korelasi >= 0,5", 
                     ifelse(abs(a$estimate) >= 0.3,"Korelasi >= 0,3",
                            ifelse(abs(a$estimate) >= 0.2,"Korelasi >= 0,2",
                                   ifelse(abs(a$estimate) >= 0.1,"Korelasi >= 0,1","Korelasi Rendah"))))
  
  # Menentukan keputusan berdasarkan p-value
  decision <- ifelse(a$p.value < 0.05, "Signifikan 5 Persen", 
                     ifelse(a$p.value < 0.1,"Signifikan 10 Persen","Tidak Signifikan"))
  
  # Menambahkan hasil ke data frame
  results_jumlah <- rbind(results_jumlah, data.frame(Variable = names(data_olahan_jumlah)[i],
                                       Correlation = a$estimate,
                                       Cutoff = as.factor(cutoff),
                                       P_Value = a$p.value,
                                       Decision = as.factor(decision)))
  
}

print(results_jumlah)
```

## Cek Korelasi Data Rasio
```{r}
# Membuat data frame kosong
results_rasio <- data.frame(Variable = character(),
                      Correlation = numeric(),
                      Cutoff = character(),
                      P_Value = numeric(),
                      Decision = character(),
                      stringsAsFactors = FALSE)

# Melakukan iterasi untuk setiap kolom dalam data_olahan_jumlah
for (i in 1:(ncol(data_olahan_rasio))) {
  # Menghitung uji korelasi
  a <- cor.test(x = data_olahan_rasio[[i]], y = data_olahan_rasio$APS_Disab, method = "spearman")
  
  # Menentukan keputusan berdasarkan p-value
  cutoff <- ifelse(abs(a$estimate) >= 0.5, "Korelasi >= 0,5", 
                     ifelse(abs(a$estimate) >= 0.3,"Korelasi >= 0,3",
                            ifelse(abs(a$estimate) >= 0.2,"Korelasi >= 0,2",
                                   ifelse(abs(a$estimate) >= 0.1,"Korelasi >= 0,1","Korelasi Rendah"))))
  
  # Menentukan keputusan berdasarkan p-value
  decision <- ifelse(a$p.value < 0.05, "Signifikan 5 Persen", 
                     ifelse(a$p.value < 0.1,"Signifikan 10 Persen","Tidak Signifikan"))
  
  # Menambahkan hasil ke data frame
  results_rasio <- rbind(results_rasio, data.frame(Variable = names(data_olahan_rasio)[i],
                                       Correlation = a$estimate,
                                       Cutoff = as.factor(cutoff),
                                       P_Value = a$p.value,
                                       Decision = as.factor(decision)))
  
}

print(results_rasio)
```

## Cek Korelasi Data Persen
```{r}
# Membuat data frame kosong
results_persen <- data.frame(Variable = character(),
                      Correlation = numeric(),
                      Cutoff = character(),
                      P_Value = numeric(),
                      Decision = character(),
                      stringsAsFactors = FALSE)

# Melakukan iterasi untuk setiap kolom dalam data_olahan_jumlah
for (i in 1:(ncol(data_olahan_persen))) {
  # Menghitung uji korelasi
  a <- cor.test(x = data_olahan_persen[[i]], y = data_olahan_persen$APS_Disab, method = "spearman")
  
  # Menentukan keputusan berdasarkan p-value
  cutoff <- ifelse(abs(a$estimate) >= 0.5, "Korelasi >= 0,5", 
                     ifelse(abs(a$estimate) >= 0.3,"Korelasi >= 0,3",
                            ifelse(abs(a$estimate) >= 0.2,"Korelasi >= 0,2",
                                   ifelse(abs(a$estimate) >= 0.1,"Korelasi >= 0,1","Korelasi Rendah"))))
  
  # Menentukan keputusan berdasarkan p-value
  decision <- ifelse(a$p.value < 0.05, "Signifikan 5 Persen", 
                     ifelse(a$p.value < 0.1,"Signifikan 10 Persen","Tidak Signifikan"))
  
  # Menambahkan hasil ke data frame
  results_persen <- rbind(results_persen, data.frame(Variable = names(data_olahan_persen)[i],
                                       Correlation = a$estimate,
                                       Cutoff = as.factor(cutoff),
                                       P_Value = a$p.value,
                                       Decision = as.factor(decision)))
  
}

print(results_persen)
```

## EBLUP Disab dengan Package "msaeDB"
```{r}
data_olahan_persen <- data_olahan_persen %>%
  mutate(
    #APS_Disab = ifelse(APS_Disab == 1, 0.9999, ifelse(APS_Disab == 0, 0.0001, APS_Disab)),
    RSE_Disab = ifelse(RSE_Disab == 0, 0.0001, RSE_Disab),
    VarDir = (APS_Disab*RSE_Disab)^2
    )



# Model dengan semua variabel yang memiliki Korelasi >= 0.2
Eblup1 <- saefh(formula = list(APS_Disab ~
                                 Persen_desa_dalam_hutan +
                                 Persen_desa_tepi_hutan +
                                 Persen_desa_luar_hutan
                              ),
              vardir = "VarDir",
              data = data_olahan_persen[-c(5,11,20,22),c(1,2,6:8,11)])

Eblup1$fit$estcoef     # estimasi paramter
aps_eblupDB <- Eblup1$SAE_Eblup$APS_Disab    # hasil pendugaan tak langsung
Eblup1$MSE_Eblup$APS_Disab    # MSE
Eblup1$randomEffect$APS_Disab # randomeffect
rse_eblupDB <- sqrt(Eblup1$MSE_Eblup$APS_Disab)/Eblup1$SAE_Eblup$APS_Disab*100    # hasil RSE pendugaan tidak langsung
```

## Perbandingan direct estimation dengan indirect estimmation
```{r}
compare <- data.frame(na.omit(data_merge[,c(1,5)]), 
                      APS_Direct = aps_eblupDB,
                      RSE_Indirect = rse_eblupDB, 
                      APS_Indirect = aps_eblupDB) %>%
  rename(RSE_Direct = RSE_Disab)

summary(compare)

gab <- left_join(kode, compare, by = "Kabupaten") %>%
  mutate(
    kat_Direct = ifelse(RSE_Direct >= 50, "Lebih dari 50 Persen",
                        ifelse(RSE_Direct >= 25, "RSE 25 - 50 Persen",
                               ifelse(RSE_Direct > 0, "RSE 0 - 25 Persen", "RSE 0"))),
    kat_Indirect = ifelse(RSE_Indirect >= 50, "Lebih dari 50 Persen",
                        ifelse(RSE_Indirect >= 25, "RSE 25 - 50 Persen",
                               ifelse(RSE_Indirect > 0, "RSE 0 - 25 Persen", "RSE 0"))),
    )

table(factor(gab$Provinsi),factor(gab$kat_Indirect))

write_sav(compare,"Hasil EBLUP.sav")
```

## Uji nomalitas random effect
```{r}
# Uji Normalitas dengan Shapiro-Wilk Test
shapiro.test(Eblup1$randomEffect$APS_Disab)

# Uji Normalitas dengan Jargue-Bera Test
tseries::jarque.bera.test(Eblup1$randomEffect$APS_Disab)

```

```{r}
ggplot(data = compare, aes(x = 1:28, y = APS.Indirect)) +
  geom_line(aes(y = APS.Indirect, color = "Indirect")) +
  geom_line(aes(y = APS.Direct, color = "Direct")) +
  labs(y = "Estimation",
       x = "ID") +
  theme_update()
```

## Clustering
```{r}
data.clust = scale(data_olahan[, c(10,16,53,58)])
kmo = function(x)
{
  x=subset(data.clust, complete.cases(x))
  r=cor(data.clust)
  r2= r^2
  i=solve(r)
  d=diag(i)
  p2= (-i/sqrt(outer(d,d)))^2
  diag(r2) <-  diag(p2) <- 0
  KMO <- sum(r2)/(sum(r2)+sum(p2))
  MSA <- colSums(r2)/(colSums(r2)+colSums(p2))
  return(list(KMO=KMO, MSA=MSA))
}

kmo(data.clust)

library(REdaS)
KMOS(data.clust)

```

```{r}
# Menentukan jumlah Cluster Terbaik
library(factoextra)
sill <- fviz_nbclust(data.clust, cluster::pam, method = "silhouette")
sill
sill$data

data_olahan <- data_olahan %>%
  mutate(
    APS_Disab = APS_Disab/100,
    VarDir = (APS_Disab*RSE_Disab)^2
  )

data_klaster <- data_olahan[,c(1,2,10,16,53,58,65)]

data_klaster <- as.data.frame(data_klaster)
rownames(data_klaster) <- data_olah$Kabupaten


library(cluster)

set.seed(123)
km_res <- pam(data.clust, 2, nstart = 20)

data_klaster$cluster <- km_res$cluster
fviz_cluster(km_res, data = data.clust)

```

```{r}
data_klaster2$cluster <- data_klaster$cluster
data_klaster2$VarDir <- ifelse(is.na(data_klaster2$VarDir), 0, data_klaster2$VarDir)
data_klaster2$APS_Disab <-  ifelse(is.na(data_klaster2$APS_Disab), 0, data_klaster2$APS_Disab)
data_klaster2$nonsample <- ifelse(data_klaster2$VarDir==0, TRUE, FALSE)
```

```{r}
saeNS <- saefhns(formula=list(APS_Disab ~
                              #keluarga_listrik +
                              #jumlah_menara_bts +
                              murid_sd +
                              #murid_smp +
                              #murid_sma +
                              #murid_slb +
                              #jumlah_sd +
                              #jumlah_smp +
                              jumlah_sma +
                              #desa_dalam_hutan +
                              #desa_tepi_hutan +
                              #desa_luar_hutan +
                              #desa_ketinggian_kurang_200 +
                              #keluarga_bukan_listrik +
                              #jumlah_SKTM +
                              #jumlah_sarana_kesehatan +
                              #jumlah_desa_tidak_ada_ponsel +
                              #jumlah_desa_lalu_lintas_lainnya +
                              #jumlah_korban_bunuh_diri +
                              #Persen_desa_dalam_hutan +
                              #Persen_desa_tepi_hutan +
                              Persen_desa_luar_hutan +
                              #Rasio_bts_luas +
                              #Rasio_murid_sd +
                              Rasio_murid_smp
                              #Rasio_nakes_faskes 
                              #Rasio_angkutan_umum_darat
                              ), 
                 vardir="VarDir", 
                 cluster="cluster", 
                 nonsample = "nonsample", 
                 data = data_klaster2)

saeNS$MSE_Eblup_all
saeNS$SAE_Eblup_all

```

```{r}
compare
```


```{r}
results %>%
  #filter(Cutoff == c("Korelasi >= 0,5", "Korelasi >= 0,3", "Korelasi >= 0,2"))
  filter(abs(Correlation) >= 0.20)

```



```{r}
data_olahan_persen <- data_olahan_persen %>%
  mutate(
    VarDir = (APS_Disab*RSE_Disab)^2,
    APS_Disab = ifelse(APS_Disab == 0, 0.0001,
                       ifelse(APS_Disab == 1, 0.9999, APS_Disab))
  )


hb1 <- saeHB::Beta(formula = APS_Disab ~ 
                     Persen_desa_dalam_hutan +
                     Persen_desa_tepi_hutan +
                     Persen_desa_luar_hutan, 
            iter.update = 100, 
            iter.mcmc = 35000, 
            thin = 25,
            burn.in = 10000, 
            data = data_olahan_persen[,c(1,2,6:8,11)])

library(coda)
plot_konvergen <- function(model){
  graphics.off()
  par("mar")
  par(mar=c(2,2,2,2))
  plot(model$plot[[3]], col="red")
  library(coda)
  autocorr.plot(model$plot[[3]],col="red")
}

plot_konvergen(hb1)
```


```{r}
# I
hb1$coefficient[,-(4:6)]
coef = as.data.frame(hb5$coefficient[,-(4:6)])
coef2 = as.data.frame(hb5$coefficient[,-(5:6)])
write_xlsx(coef, "coef.xlsx")
write_xlsx(coef2, "coef2.xlsx")
```


```{r}
# II
hb1$Est$MEAN
est_mean = as.data.frame(hb5$Est$MEAN)
write_xlsx(est_mean, "est_mean.xlsx")
```


```{r}
# III
hb1$refVar
```


```{r}
# IV
hb5$Est$SD
est_sd = as.data.frame(hb5$Est$SD)
write_xlsx(est_sd, "est_sd.xlsx")
```


```{r}
# V
rse_hb1<-hb1$Est$SD/hb1$Est$MEAN*100
rse_dis = as.data.frame(rse_hb1)
write_xlsx(rse_dis, "rse_dis.xlsx")

# VI
summary(rse_hb1) # clear, semua RSE < 25%

# VII
summary(hb1)
```

