---
title: "Modeling NTB"
author: "Group 3"
date: "`r Sys.Date()`"
output: html_document
---
# DATASET
## Dataset Provinsi NTB
```{r}
NTB_data_olahan_rasio <- data_olah[c(1:10),c(5,6,61:69)]
NTB_data_olahan_persen <- data_olah[c(1:10),c(5,6,53:60)]
NTB_data_olahan_jumlah <- data_olah[c(1:10),c(5,6,8:13,15:22,24:30,32,35,38:41,43,46,48:50)]
```


# DATA JUMLAH
## Cek Korelasi Data Jumlah (NTB)
```{r}
# Membuat data frame kosong
NTB_cor_jumlah <- data.frame(Variable = character(),
                      Correlation = numeric(),
                      Cutoff = character(),
                      P_Value = numeric(),
                      Decision = character(),
                      stringsAsFactors = FALSE)

# Melakukan Pengecekan Korelasi Provinsi NTT - data Jumlah
for (i in 1:(ncol(NTB_data_olahan_jumlah))) {
  # Menghitung uji korelasi
  a <- cor.test(x = NTB_data_olahan_jumlah[[i]], y = NTB_data_olahan_jumlah$APS_Disab, method = "spearman")
  
  cutoff <- ifelse(abs(a$estimate) >= 0.5, "Korelasi >= 0,5", 
                     ifelse(abs(a$estimate) >= 0.3,"Korelasi >= 0,3",
                            ifelse(abs(a$estimate) >= 0.2,"Korelasi >= 0,2",
                                   ifelse(abs(a$estimate) >= 0.1,"Korelasi >= 0,1","Korelasi Rendah"))))
  
  decision <- ifelse(a$p.value < 0.05, "Signifikan 5 Persen", 
                     ifelse(a$p.value < 0.1,"Signifikan 10 Persen","Tidak Signifikan"))
  
  NTB_cor_jumlah <- rbind(NTB_cor_jumlah, data.frame(Variable = names(NTB_data_olahan_jumlah)[i],
                                       Correlation = a$estimate,
                                       Cutoff = as.factor(cutoff),
                                       P_Value = a$p.value,
                                       Decision = as.factor(decision)))
}

NTB_cor_jumlah %>%
  filter(abs(Correlation) >=0.5)

```

```{r}
# Korelasi 0.5 keatas
car::vif(
lm(APS_Disab ~ 
     jumlah_rs +
     desa_tepi_hutan +
     #desa_penerangan_jalan +
     #jumlah_tenaga_kesehatan +
     #jumlah_faskes +
     jumlah_desa_sinyal_kuat,
     #jumlah_desa_lalu_lintas_darat +
     #jumlah_desa_angkutan_umum,
     data = NTB_data_olahan_jumlah)
)

```

## SAE HB Beta NTT
```{r}
set.seed(123)

NTB_HB_jumlah <- NTB_data_olahan_jumlah %>%
  mutate(
    APS_Disab = ifelse(APS_Disab == 0, 0.0001,
                       ifelse(APS_Disab == 1, 0.9999, APS_Disab))
  )

# Menggunakan 4 Variabel
NTB_HB1 <- saeHB::Beta(formula = APS_Disab ~ 
                        desa_tepi_hutan +
                        jumlah_rs +
                        jumlah_desa_lalu_lintas_darat, 
                   iter.update = 200, 
                   iter.mcmc = 50000, 
                   thin = 25,
                   burn.in = 10000, 
                   data = NTB_HB_jumlah)

```

## Pengecekan Hasil SAE HB
```{r}
# Cek Koefisien
NTB_HB1$coefficient[,-(4:6)]

# Cek Indirect
NTB_HB1$Est$MEAN

# Cek Standar Deviasi
NTB_HB1$Est$SD

# Cek RSE
summary(
  as.data.frame(NTB_HB1$Est$SD/NTB_HB1$Est$MEAN*100) %>%
  mutate(
    RSE = as.factor(ifelse(NTB_HB1$Est$SD/NTB_HB1$Est$MEAN*100 >= 50, ">=50%",
                           ifelse(NTB_HB1$Est$SD/NTB_HB1$Est$MEAN*100 >= 25, ">=25%",
                                  "<25%")))
    )
)

```

## Simpan Hasil Terbaik
```{r}
# Simpan Hasil
NTB_HB1$Est$RSE <- NTB_HB1$Est$SD/NTB_HB1$Est$MEAN*100
NTB_hasil_jumlah <- NTB_HB1$Est[,-c(4:6)]
write.csv(NTB_hasil_jumlah, "NTB_hasil_jumlah.csv")
```


# DATA RASIO
## Cek Korelasi Data Rasio (NTB)
```{r}
# Membuat data frame kosong
NTB_cor_rasio <- data.frame(Variable = character(),
                      Correlation = numeric(),
                      Cutoff = character(),
                      P_Value = numeric(),
                      Decision = character(),
                      stringsAsFactors = FALSE)

# Melakukan Pengecekan Korelasi Provinsi NTT - data Jumlah
for (i in 1:(ncol(NTB_data_olahan_rasio))) {
  # Menghitung uji korelasi
  a <- cor.test(x = NTB_data_olahan_rasio[[i]], y = NTB_data_olahan_rasio$APS_Disab, method = "spearman")
  
  cutoff <- ifelse(abs(a$estimate) >= 0.5, "Korelasi >= 0,5", 
                     ifelse(abs(a$estimate) >= 0.3,"Korelasi >= 0,3",
                            ifelse(abs(a$estimate) >= 0.2,"Korelasi >= 0,2",
                                   ifelse(abs(a$estimate) >= 0.1,"Korelasi >= 0,1","Korelasi Rendah"))))
  
  decision <- ifelse(a$p.value < 0.05, "Signifikan 5 Persen", 
                     ifelse(a$p.value < 0.1,"Signifikan 10 Persen","Tidak Signifikan"))
  
  NTB_cor_rasio <- rbind(NTB_cor_rasio, data.frame(Variable = names(NTB_data_olahan_rasio)[i],
                                       Correlation = a$estimate,
                                       Cutoff = as.factor(cutoff),
                                       P_Value = a$p.value,
                                       Decision = as.factor(decision)))
}

NTB_cor_rasio %>%
  filter(abs(Correlation)>=0.3)

```

```{r}
# Korelasi 0.3 keatas
car::vif(
lm(APS_Disab ~ 
     Rasio_murid_smp +
     Rasio_murid_slb +
     Rasio_nakes_faskes +
     Rasio_angkutan_umum_darat,
     data = NTB_data_olahan_rasio)
)
```

## SAE HB Beta NTB
```{r}
NTB_HB_rasio <- NTB_data_olahan_rasio %>%
  mutate(
    APS_Disab = ifelse(APS_Disab == 0, 0.0001,
                       ifelse(APS_Disab == 1, 0.9999, APS_Disab))
  )

# Menggunakan Korelasi >= 30 persen
NTB_HB3 <- saeHB::Beta(formula = APS_Disab ~ 
                        Rasio_murid_smp +
                        Rasio_murid_slb +
                        Rasio_nakes_faskes +
                        Rasio_angkutan_umum_darat, 
                   iter.update = 100, 
                   iter.mcmc = 50000, 
                   thin = 25,
                   burn.in = 10000, 
                   data = NTB_HB_rasio)

# Menggunakan Korelasi >= 50 persen
NTB_HB4 <- saeHB::Beta(formula = APS_Disab ~ 
                        Rasio_murid_smp +
                        Rasio_nakes_faskes, 
                   iter.update = 100, 
                   iter.mcmc = 50000, 
                   thin = 25,
                   burn.in = 10000, 
                   data = NTB_HB_rasio)

```

## Pengecekan Hasil SAE HB
```{r}
set.seed(123)

# Cek Koefisien
NTB_HB3$coefficient[,-(4:6)]

# Cek Indirect
NTB_HB3$Est$MEAN

# Cek Standar Deviasi
NTB_HB3$Est$SD

# Cek RSE
summary(
  as.data.frame(NTB_HB3$Est$SD/NTB_HB3$Est$MEAN*100) %>%
  mutate(
    RSE = as.factor(ifelse(NTB_HB3$Est$SD/NTB_HB3$Est$MEAN*100 >= 50, ">=50%",
                           ifelse(NTB_HB3$Est$SD/NTB_HB3$Est$MEAN*100 >= 25, ">=25%",
                                  "<25%")))
    )
)

```

```{r}
# Cek Koefisien
NTB_HB4$coefficient[,-(4:6)]

# Cek Indirect
NTB_HB4$Est$MEAN

# Cek Standar Deviasi
NTB_HB4$Est$SD

# Cek RSE
summary(
  as.data.frame(NTB_HB4$Est$SD/NTB_HB4$Est$MEAN*100) %>%
  mutate(
    RSE = as.factor(ifelse(NTB_HB4$Est$SD/NTB_HB4$Est$MEAN*100 >= 50, ">=50%",
                           ifelse(NTB_HB4$Est$SD/NTB_HB4$Est$MEAN*100 >= 25, ">=25%",
                                  "<25%")))
    )
)

```
## Simpan Hasil Terbaik
```{r}
# Simpan Hasil
# NTB_HB4$Est$RSE <- NTB_HB6$Est$SD/NTB_HB6$Est$MEAN*100
# NTB_hasil_rasio <- NTB_HB6$Est[,-c(4:6)]
# write.csv(NTB_hasil_rasio, "NTB_hasil_rasio(1).csv")
```


# DATA PERSEN
## Cek Korelasi Data Persen (NTB)
```{r}
# Membuat data frame kosong
NTB_cor_persen <- data.frame(Variable = character(),
                      Correlation = numeric(),
                      Cutoff = character(),
                      P_Value = numeric(),
                      Decision = character(),
                      stringsAsFactors = FALSE)

# Melakukan Pengecekan Korelasi Provinsi NTT - data Jumlah
for (i in 1:(ncol(NTB_data_olahan_persen))) {
  # Menghitung uji korelasi
  a <- cor.test(x = NTB_data_olahan_persen[[i]], y = NTB_data_olahan_persen$APS_Disab, method = "spearman")
  
  cutoff <- ifelse(abs(a$estimate) >= 0.5, "Korelasi >= 0,5", 
                     ifelse(abs(a$estimate) >= 0.3,"Korelasi >= 0,3",
                            ifelse(abs(a$estimate) >= 0.2,"Korelasi >= 0,2",
                                   ifelse(abs(a$estimate) >= 0.1,"Korelasi >= 0,1","Korelasi Rendah"))))
  
  decision <- ifelse(a$p.value < 0.05, "Signifikan 5 Persen", 
                     ifelse(a$p.value < 0.1,"Signifikan 10 Persen","Tidak Signifikan"))
  
  NTB_cor_persen <- rbind(NTB_cor_persen, data.frame(Variable = names(NTB_data_olahan_persen)[i],
                                       Correlation = a$estimate,
                                       Cutoff = as.factor(cutoff),
                                       P_Value = a$p.value,
                                       Decision = as.factor(decision)))
}

NTB_cor_persen %>%
  filter(abs(Correlation)>=0.3)

```

```{r}
# Korelasi 0.3 keatas
car::vif(
lm(APS_Disab ~ 
     Persen_desa_dalam_hutan +
     Persen_desa_tepi_hutan,
     data = NTB_data_olahan_persen)
)
```

## SAE HB Beta NTT
```{r}
set.seed(123)

NTB_HB_persen <- NTB_data_olahan_persen %>%
  mutate(
    APS_Disab = ifelse(APS_Disab == 0, 0.0001,
                       ifelse(APS_Disab == 1, 0.9999, APS_Disab))
  )


# Menggunakan 4 Variabel
NTB_HB5 <- saeHB::Beta(formula = APS_Disab ~ 
                        Persen_desa_dalam_hutan +
                        Persen_desa_tepi_hutan, 
                   iter.update = 100, 
                   iter.mcmc = 50000, 
                   thin = 25,
                   burn.in = 10000, 
                   data = NTB_HB_persen)

# Menggunakan 2 Variabel
NTB_HB6 <- saeHB::Beta(formula = APS_Disab ~ 
                        persen_perkotaan +
                        Persen_desa_dalam_hutan +
                        Persen_desa_luar_hutan, 
                   iter.update = 100, 
                   iter.mcmc = 50000, 
                   thin = 25,
                   burn.in = 10000, 
                   data = NTB_HB_persen)

```

## Pengecekan Hasil SAE HB
```{r}
# Cek Koefisien
NTB_HB5$coefficient[,-(4:6)]

# Cek Indirect
NTB_HB5$Est$MEAN

# Cek Standar Deviasi
NTB_HB5$Est$SD

# Cek RSE
summary(
  as.data.frame(NTB_HB5$Est$SD/NTB_HB5$Est$MEAN*100) %>%
  mutate(
    RSE = as.factor(ifelse(NTB_HB5$Est$SD/NTB_HB5$Est$MEAN*100 >= 50, ">=50%",
                           ifelse(NTB_HB5$Est$SD/NTB_HB5$Est$MEAN*100 >= 25, ">=25%",
                                  "<25%")))
    )
)
```

```{r}
# Cek Koefisien
NTB_HB6$coefficient[,-(4:6)]

# Cek Indirect
NTB_HB6$Est$MEAN

# Cek Standar Deviasi
NTB_HB6$Est$SD

# Cek RSE
summary(
  as.data.frame(NTB_HB6$Est$SD/NTB_HB6$Est$MEAN*100) %>%
  mutate(
    RSE = as.factor(ifelse(NTB_HB6$Est$SD/NTB_HB6$Est$MEAN*100 >= 50, ">=50%",
                           ifelse(NTB_HB6$Est$SD/NTB_HB6$Est$MEAN*100 >= 25, ">=25%",
                                  "<25%")))
    )
)
```

## Simpan Hasil Terbaik
```{r}
# Simpan Hasil
# NTB_HB6$Est$RSE <- NTB_HB6$Est$SD/NTB_HB6$Est$MEAN*100
# NTB_hasil_persen <- NTB_HB6$Est[,-c(4:6)]
# write.csv(NTB_hasil_rasio, "NTB_hasil_rasio(1).csv")
```

