---
title: "Modeling NTB"
author: "Group 3"
date: "`r Sys.Date()`"
output: html_document
---

## Dataset Provinsi NTT
```{r}
NTB_data_olahan_rasio <- data_olah[c(11:32),c(5,6,61:71)]
NTB_data_olahan_persen <- data_olah[c(11:32),c(5,6,53:60)]
NTB_data_olahan_jumlah <- data_olah[c(11:32),c(5,6,8:13,15:22,24:30,32,35,38:41,43,46,48:50)]
```

## Cek Korelasi Data Jumlah (NTT)
```{r}
# Membuat data frame kosong
NTT_cor_jumlah <- data.frame(Variable = character(),
                      Correlation = numeric(),
                      Cutoff = character(),
                      P_Value = numeric(),
                      Decision = character(),
                      stringsAsFactors = FALSE)

# Melakukan Pengecekan Korelasi Provinsi NTT - data Jumlah
for (i in 1:(ncol(NTT_data_olahan_jumlah))) {
  # Menghitung uji korelasi
  a <- cor.test(x = NTT_data_olahan_jumlah[[i]], y = NTT_data_olahan_jumlah$APS_Disab, method = "spearman")
  
  cutoff <- ifelse(abs(a$estimate) >= 0.5, "Korelasi >= 0,5", 
                     ifelse(abs(a$estimate) >= 0.3,"Korelasi >= 0,3",
                            ifelse(abs(a$estimate) >= 0.2,"Korelasi >= 0,2",
                                   ifelse(abs(a$estimate) >= 0.1,"Korelasi >= 0,1","Korelasi Rendah"))))
  
  decision <- ifelse(a$p.value < 0.05, "Signifikan 5 Persen", 
                     ifelse(a$p.value < 0.1,"Signifikan 10 Persen","Tidak Signifikan"))
  
  NTT_cor_jumlah <- rbind(NTT_cor_jumlah, data.frame(Variable = names(NTT_data_olahan_jumlah)[i],
                                       Correlation = a$estimate,
                                       Cutoff = as.factor(cutoff),
                                       P_Value = a$p.value,
                                       Decision = as.factor(decision)))
  
}

NTT_cor_jumlah %>%
  filter(abs(Correlation) >= 0.3)
```

```{r}

```

